### ISSUE TITLE
gridpad with only columns available

### ISSUE THREAD

**Issue by hilmanshini** [touchlane/gridpad-android#18]
is there any possibility to provide the feature to make the gridpad only receive the column parameter? (as the row would be unknown count)

**Comment by landarskiy** [comment]
> hilmanshini

Hi! Thank you for your question. Can you share with me a case you try to solve? Maybe there is another way to chive your goal. And what’s your expectations about layout behavior? 
The thing here in previous versions the following syntax was acceptable:
```
item(row = 1) {
        // cell content
}
```
But API above was deprecated and removed in new versions due to unclear behavior (because of the complex rules of implicit cell placement with spans > 1)

**Comment by landarskiy** [comment]
I'm closing this discussion due to lack of activity. Please reopen it if you still have questions.
